### ISSUE TITLE
Specific assembly exception

### ISSUE THREAD

**Issue by federinik** [Yortw/Yort.Ntp#2]
Hi, when I invoke the BeginRequestTime method of an NTPClient object I get this exception:

"This assembly should never be loaded at runtime, and should only be referenced from other portable class libraries. Please ensure your application references a platform specific assembly."

**Comment by Yortw** [comment]
It looks like your reference to the Yort.NTP dll is incorrect (wrong DLL referenced).
That error occurs when you've referenced the PCL dll from your app. The PCL dll should only ever be referenced from other PCL projects, your main app/website etc should reference the DLL for the nearest non portable DLL (i.e the full .Net 4 version for example).

The Nuget package _should_ add the correct references for you. 

Are you using the Nuget package?
What type of project do you have/which framework are you targeting/

**Comment by federinik** [comment]
I'm using Yort in 3 different project, SL 8.1, WinRT 8.1 and UWP apps. I'm using the NuGet package, but the only package I'm able to find on NuGet it's Yort.Ntp.Portable.

At this moment, I've downloaded the source code and imported it in my project but I would like to integrate Yort through the NuGet package

**Comment by Yortw** [comment]
Does this occur for all three projects, or just one or two?
Can you check the references?
The SL8.1 project should reference Yort.Ntp.WPSL.dll
The WinRT and UWP should both reference Yort.Ntp.dll but in the lib\netcore451 folder under wherever the nuget package contents are stored on your machine.

Nothing should reference anything in lib\portable-net45+win+wpa81+wp80

**Comment by Yortw** [comment]
Hi,

Did you manage to check the references?

**Comment by federinik** [comment]
Hi,
I'm sorry but I've been kinda busy at work, while I'm using Yort for a personal project. I'll keep you updated asap I have checked the references

**Comment by Yortw** [comment]
No problem, I know how that is :)

**Comment by federinik** [comment]
Ok, here are the references:
- RT project references Yort.Ntp, path ...\packages\Yort.Ntp.Portable.1.0.6\lib\portable-net45+win+wpa81+wp80\Yort.Ntp.dll
- SL project references Yort.Ntp.Portable, path ...\Yort.Ntp.Portable.1.0.6\lib\wp81\Yort.Ntp.WPSL.dll
- UWP project references Yort.Ntp.Portable, path (I think, properties from Visual Studio are empty, so that's from project.lock.json) lib/netcore451/Yort.Ntp.dll

Maybe the NuGet packages directives for RT are wrong?

**Comment by Yortw** [comment]
Hmmm odd. I just tried a brand new UWP project and a brand new WinRT 8.1 project.
The UWP and Windows WinRT 8.1 projects reference the assembly in the netcore451 folder, which should be correct, they don't reference the portable one like you have - I'm not sure why you're getting those references.

Also tried it with an SL8.1 phone app, and it references; lib\wp81\Yort.Ntp.WPSL.dll - so also not the portable one.

The WP WinRT 8.1 project did reference the portable assembly, so I'll need to figure out how to update nuget package to do the right thing there.

If you remove and re-add the package does that help?
What version of nuget do you have installed?

**Comment by federinik** [comment]
I've removed-added the package many times and nothing has changed. NuGet is v. 3.4.3. Visual Studio is 2015 v. 14.0.25123 Update 2

A brand new WinRT8.1 project of mine references ...\portable-net45+win+wpa81+wp80\Yort.Ntp.dll

Edit: closed by mistake, reopened

**Comment by Yortw** [comment]
Weird. I have the same versions but seem to get different behaviour. I'll try to do more testing when I get some time.
You should be able to fix the problem temporarily by manually changing the references.

Thanks for assisting by providing detail.

**Comment by federinik** [comment]
No problem, I wish to help you so I can use the NuGet package instead of the source

**Comment by Yortw** [comment]
Hi,

Does your RT project target 8.1 or 8.0?

**Comment by Yortw** [comment]
Also is your RT project a 'phone RT' project?

**Comment by Yortw** [comment]
I've pushed a new copy to nuget that _might_ fix it, but I can still only reproduce the issue on a WPA8.1 project, the others appear to be fine. Let me know if the updated version helps.

**Comment by federinik** [comment]
My project targets 8.1 and it's a phone project, not Universal. I'll try the new package asap

**Comment by Yortw** [comment]
Hi, any luck with using the new package?

**Comment by federinik** [comment]
Hi, sorry for taking so long to answer you. First of all, after the update of NuGet package to v 1.0.7 my SL project won't compile anymore. All the classes from the Yort.Ntp namespace are ambiguously located in Yort.Ntp and Yort.Ntp.WPSL dll's, both of them figure in the references section of my SL project.

In addition, my WInRT project compiles, but when try to use the class NtpClient, this exception is thrown:

Could not load file or assembly 'Yort.Ntp, Version=1.0.0.7, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Just Yort.Ntp dll is referenced in my RT project.

**Comment by federinik** [comment]
Hi, sorry for taking so long to answer you. First of all, after the update of NuGet package to v 1.0.7 my SL project won't compile anymore. All the classes from the Yort.Ntp namespace are ambiguously located in Yort.Ntp and Yort.Ntp.WPSL dll's, both of them figure in the references section of my SL project.

In addition, my WInRT project compiles, but when try to use the class NtpClient, this exception is thrown:

Could not load file or assembly 'Yort.Ntp, Version=1.0.0.7, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Just Yort.Ntp dll is referenced in my RT project. I've cleaned/rebuilt my project and reinstalled from 0 my apps difefrent times.

**Comment by Yortw** [comment]
Thanks for getting back to me. I'm at work now so unfortunately it will be later tonight my time (NZ) before I can look further. It definitely still sounds like you're getting bad references though. I'll get back to you when I know more.

**Comment by Yortw** [comment]
Hi,

I found a problem with the Nuget package with regards to WPSL and .Net 4.5 projects. 

I've pushed a new package to fix that. I wasn't able to reproduce the RT problem, but possibly the package changes will help anyway. I created a new solution with a WPSL8.1, WinRT8.1 and WinRTPhone8.1 project and applied the updated package - all of them compiled and actually retrieved times from the internet.

Please give the new package a try when you have time and let me know if it works.

**Comment by federinik** [comment]
Hi, sorry again for taking all this time to answer you.

NuGet package 1.0.9 solved all the problems mentioned above. Closing the issue, thank you.

**Comment by Yortw** [comment]
Excellent, thanks for reporting the issue and letting me know the last update fixed it.
