### ISSUE TITLE
Socket unsubscription to OnMessageReceived throws Exception "A method was called at an unexpected time."

### ISSUE THREAD

**Issue by federinik** [Yortw/Yort.Ntp#4]
Hi,
on Windows Phone 8.1 (RT) class `NtpClient`(_NtpClientWinRTSockets.cs_) throws Exception with description "A method was called at an unexpected time.".

I found this post on SO

http://stackoverflow.com/questions/16147904/how-to-unsubscribe-from-datagramsocket-messagereceived-event

where the guideline it's to just don't subscribe from the event, the .Dispose() will do the job. I suggest to follow this approach, cause it's working for me. I commented 

`socket.MessageReceived -= this.Socket_Completed_Receive;`

in file _NtpClientWinRTSockets.cs_.

Best regards

**Comment by Yortw** [comment]
Hi,

Are you using the latest version?

The latest version of the WinRT code for this library does the following;

ExecuteWithSuppressedExceptions(() => socket.MessageReceived -= this.Socket_Completed_Receive);

The ExecuteWithSuppressedExceptions should hide that exception _if_ it occurs (it is intermittent in my experience), so it should not cause a problem. If you have 'break on all exceptions' enabled you might see the exception in the debugger but should be able to ignore it and continue. 

I prefer to remove the event handler when possible to avoid _potential_ memory leaks (I am not sure the socket object uses a weak event handler reference). Neither Dispose nor setting our reference to the socket to null are likely to clean up the event handler reference (though I don't know for sure what it's Dispose method does internally), so they don't necessarily solve that issue.

**Comment by federinik** [comment]
Hi, package 1.0.9 solved the problem.

Thank you

**Comment by Yortw** [comment]
Excellent, thanks for letting me know.
