### ISSUE TITLE
NTP SocketError.Error else block and event

### ISSUE THREAD

**Issue by codingyourlife** [Yortw/Yort.Ntp#6]
FEATURE REQUEST

In this file:
https://github.com/Yortw/Yort.Ntp/blob/master/src/Yort.Ntp.Portable/NtpClient.cs

There is no event if synchronization fails. There is only if(e.SocketError == SocketError.Success) but no else. It would be nice to have an event if e.g. server is down to create a fallback mechanism for another NTP server.

**Comment by Yortw** [comment]
Hi,

That file is not actually used any more (should be deleted from the repo). The portable library is now just a bait library, and the platform specific libraries are used at runtime. Opening the solution in VS will show that file isn't loaded in the portable project. All of the actual NtpClient code that is being compiled into assemblies has an 'else' condition on those statements which raises the ErrorOcurred event.

For the actual implementation being used, see the files;
https://github.com/Yortw/Yort.Ntp/blob/master/src/Yort.Ntp.Shared.StandardSockets/NtpClientStandardSockets.cs

https://github.com/Yortw/Yort.Ntp/blob/master/src/Yort.Ntp.WinRT/NtpClientWinRTSockets.cs

If you're not seeing the ErrorOccured event raised under some condition, could you please advise the platform & conditions required to reproduce?

Thanks.

**Comment by Yortw** [comment]
For example, this code should fail as the host cannot be resolved, and the ErrorOcurred event should be raised which will then write the exception details to the debug window. I tested this in a desktop console app.

```c#
		static void Main(string[] args)
		{
			Yort.Ntp.NtpClient c = new Yort.Ntp.NtpClient("notanntpserver");
			c.ErrorOccurred += client_ErrorOccurred;
			c.BeginRequestTime();
		}

		private static void client_ErrorOccurred(object sender, Yort.Ntp.NtpNetworkErrorEventArgs e)
		{
			System.Diagnostics.Debug.WriteLine(e.Exception.ToString());
		}
```

**Comment by codingyourlife** [comment]
I didn't test it yet but when I looked at the wrong file and it is implemented in the NuGet package that I get this is closed for me. Thanks!

**Comment by Yortw** [comment]
No problem, that file should have been removed earlier but somehow I missed it when implementing that change.

Thanks for reporting the potential issue.
