### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by kvpt** [Yortw/Yort.Ntp#8]
Hi,

I use this library in an application (Xamarin) deployed on mobile devices, which may have network connection reliability issues.

It works great 99.99%, but sometime in my api, I receive call from the app with invalid dates.
For example :
- 01/01/1900 01:05:12
- 01/01/1900 01:04:55
- 01/01/1900 00:32:17

I found in the code [here](https://github.com/Yortw/Yort.Ntp/blob/fd68ae786bd36bd1ffdabadae968dab3a837b2c0/src/Yort.Ntp.SharedImplementation/NtpClient.cs#L204) that the default time is 01/01/1900, so I suspect an incomplete buffer to cause this issue.

My question is how to handle this case ?

A/ An exception must be raised by the library
B/ Date must be verified by user code

**Comment by Yortw** [comment]
Hi,

Thanks for the bug report. I believe the correct behaviour is for the library to throw an exception or raise the exception event, and **not** raise the time event providing an incorrect time in the scenario described. Unfortunately this is not something I've experienced myself, so I will need to find time to reproduce and/or study the code to find a way to detect the problem and handle it appropriately.

Thanks again.

**Comment by Yortw** [comment]
Hi,

I've just pushed an update that I hope fixes this. Please let me know if you still experience it on the new version.

Thanks.
